#ifndef BITEVOLVER_DEFINES_H
#define BITEVOLVER_DEFINES_H



//
#define BIT_EVOLVER_POPULATION_DEFAULT_POPULATION_SIZE				100
#define BIT_EVOLVER_POPULATION_DEFAULT_MUTATE_RATE					0.01
#define BIT_EVOLVER_POPULATION_DEFAULT_CROSSOVER					0.7



#endif